<a href="https://colab.research.google.com/github/ebzkurt1/ml_with_jax/blob/main/Perceptron_using_Jax_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import jax
from jax import random
import jax.numpy as jnp
from jax import grad, jit, vmap

In [2]:
key = random.PRNGKey(0)
x = random.normal(key, (10,))
print(x)

[-0.3721109   0.26423115 -0.18252768 -0.7368197  -0.44030377 -0.1521442
 -0.67135346 -0.5908641   0.73168886  0.5673026 ]


In [15]:
def forward(X,w,b):
    return jnp.matmul(X,w)+b

def sig(fwd):
    return 1/(1+jnp.exp(-fwd))

def loss_fnc(yhat,y):
    return jnp.mean((yhat-y)**2)


In [43]:
X = jnp.array([[3.0,1.2,3.6],[1.4,6.21,6.8],[1.4,67.3,8.9],[1.4,2.6,1.6]])
y = jnp.array([[1.2],[5.1],[7.3]])
class_num = 3
W = random.normal(key=random.PRNGKey(42),shape=(X.shape[-1],class_num))
b = random.normal(key=random.PRNGKey(42),shape=(class_num,1))
print(b)
print(jnp.matmul(X,W))
ff = (jnp.matmul(X,W).T + b).T
pred = jnp.exp(ff)/jnp.exp(ff).sum(axis=0)
pred_arg = jnp.argmax(pred,axis=1).reshape(-1,1)
print(pred_arg)

[[ 0.18693547]
 [-1.2806505 ]
 [-1.5593132 ]]
[[  1.1221201  -3.0668693  -2.4274304]
 [  5.3090363  -1.4732898  -4.3279586]
 [ 78.27431    33.596214  -56.818012 ]
 [  3.020036   -0.159982   -2.936196 ]]
[[2]
 [2]
 [0]
 [2]]


In [ ]:
def custom_sigmoid(matrix):
    return (1/(1+jnp.exp(-matrix)))

def custom_softmax(matrix):
    return jnp.exp(matrix)/jnp.exp(matrix).sum(axis=0)

def forward_pass(X, W, b, activation_func):
    return activation_func((jnp.matmul(X, W).T + b).T)

def categorical_cross_entrop(yhat)

def loss_fnc(X, W, b, activation, loss_func):
    yhat = forward_pass(X,W,b,activation)


In [ ]:
class Perceptron:
    def __init__(self, activation_func='sigmoid', loss_func='mean_squared_error', learning_rate=0.01, iter=50, random_key=1):
        self.activation_func = activation_func
        self.loss_func = loss_func
        self.learning_rate = learning_rate
        self.iter = iter
        self.random_key = random.PRNGKey(random_key)

    def forward(self, X):
        return jnp.matmul(X, self.w) + self.b

    def sigmoid_func(matrix):
        return (1/(1+jnp.exp(-matrix)))

    def jax_sigmoid(matrix):
        return jax.nn.sigmoid(matrix)
    
    def mean_squared_error(yhat, y):
        return jnp.mean((yhat-y)**2)
    
    def param_update(self, gradient):
        self.w -= self.learning_rate * gradient
        self.b -= 

    def fit(self, X, Y):
        self.w = random.normal(
            key=self.random_key,
            shape=(X.shape[-1],1)
        )
        self.b = random.normal(
            key=self.random_key
        )

        for _ in range(self.iter):
            error = 0
            forward_pass = forward(self, X)
            if self.activation_func == 'sigmoid':
                activation = sigmoid_func(forward_pass)
            else:
                activation = forward_pass
            if self.loss_func == 'mean_squared_error':
                gradient_func = grad(mean_squared_error)
                gradient = gradient_func(activation)
            else:
                pass